query GetGenres($input: GetGenresInput) {
  getGenres(input: $input) {
    childGenres {
      id
    }
    id
    databaseId
    description
    name
    ratio
    color
    parentGenre {
      id
    }
  }
}