query GetGenreDetailPageData($input: GetGenreSetInput!) {
  getGenreSet(input: $input) {
    ...GenreSetData
    genres {
      ...GenreData
      parentGenre {
        id
      }
      childGenres {
        id
      }
      createdAt
    }
  }
}

