query GetQuizLists($input: GetQuizListsInput) {
  getQuizLists(input: $input) {
    description
    name
    databaseId
    id
    goal
    quizCount
    genreSet {
      name
      id
      databaseId
    }
  }
}