query GetQuiz($input: GetQuizInput) {
  getQuiz(input: $input) {
    explanation
    databaseId
    answer
    otherAnswer
    source
    id
    question
    genre {
      name
      id
      databaseId
    }
  }
}