query GetGenresFromQuizList($input: GetQuizListInput) {
  getQuizList(input: $input) {
    genreSet {
      genres {
        color
        parentGenre {
          id
          databaseId
        }
        childGenres{
          id
          databaseId
        }
        id
        databaseId
        description
        name
      }
    }
  }
}