query GetQuizzes($input: GetQuizzesInput!) {
  getQuizzes(input: $input) {
    answer
    databaseId
    explanation
    otherAnswer
    source
    id
    question
    genre {
      name
      databaseId
      id
      color
    }
  }
}
