query GetQuizListStatData($input: GetQuizListInput) {
  getQuizList(input: $input) {
    id
    databaseId
    goal
    quizCount
    quizzes {
      genre {
        id
      }
    }
    genreSet {
      genres {
        id
        databaseId
        color
        name
        ratio
        childGenres {
          id
        }
        parentGenre {
          id
        }
      }
    }
  }
}